# Generated by Django 6.0.3 on 2026-04-09 05:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditationapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedgroup',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='useridentity',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='savedgroup',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='meditationapp_savedgroup_user_group_uniq'),
        ),
        migrations.AddConstraint(
            model_name='useridentity',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='meditationapp_useridentity_provider_uid_uniq'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'group'), name='meditationapp_userrole_user_role_group_uniq'),
        ),
    ]
