# Generated by Django 6.0.3 on 2026-04-14 01:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditationapp', '0002_alter_savedgroup_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useridentity',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='useridentity',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='useridentity',
            name='token_expires_at',
        ),
        migrations.AddField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='session',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='meditationgroup',
            name='cost_type',
            field=models.CharField(choices=[('free', 'Free'), ('donation', 'Donation')], max_length=8),
        ),
        migrations.AlterField(
            model_name='meditationgroup',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='meditationgroup',
            name='postcode',
            field=models.CharField(db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='meditationgroup',
            name='source',
            field=models.CharField(choices=[('scrape', 'Scrape'), ('self', 'Self')], max_length=6),
        ),
        migrations.AlterField(
            model_name='meditationgroup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='meditationgroup',
            name='style',
            field=models.CharField(choices=[('mindfulness', 'Mindfulness'), ('zen', 'Zen'), ('guided_breathing', 'Guided breathing')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='meditationgroup',
            name='suburb',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='session',
            name='style',
            field=models.CharField(blank=True, choices=[('mindfulness', 'Mindfulness'), ('zen', 'Zen'), ('guided_breathing', 'Guided breathing')], max_length=16, null=True),
        ),
    ]
