# Generated by Django 6.0.3 on 2026-04-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditationapp', '0003_remove_useridentity_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='recurrence_pattern',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
