# Generated by Django 6.0.3 on 2026-04-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditationapp', '0004_session_is_recurring_session_recurrence_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='beginner_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meditationgroup',
            name='cost_type',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('donation', 'Donation')], max_length=8),
        ),
        migrations.AlterField(
            model_name='meditationgroup',
            name='style',
            field=models.CharField(choices=[('mindfulness', 'Mindfulness'), ('zen', 'Zen'), ('guided_breathing', 'Guided breathing'), ('yoga_nidra', 'Yoga nidra')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='session',
            name='style',
            field=models.CharField(blank=True, choices=[('mindfulness', 'Mindfulness'), ('zen', 'Zen'), ('guided_breathing', 'Guided breathing'), ('yoga_nidra', 'Yoga nidra')], max_length=16, null=True),
        ),
    ]
