# Generated by Django 6.0.3 on 2026-04-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditationapp', '0007_pipeline_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='recurrence',
            field=models.CharField(choices=[('one_off', 'One-off'), ('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly'), ('irregular', 'Irregular')], db_index=True, default='one_off', max_length=16),
        ),
        migrations.AddField(
            model_name='session',
            name='recurrence_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='recurrence_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='candidaterecord',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('keyword_passed', 'Keyword passed'), ('quality_passed', 'Quality passed'), ('extraction_ready', 'Extraction ready'), ('extraction_passed', 'Extraction passed'), ('needs_review', 'Needs review'), ('promoted', 'Promoted'), ('failed', 'Failed')], db_index=True, default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='extractionattempt',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('keyword_passed', 'Keyword passed'), ('quality_passed', 'Quality passed'), ('extraction_ready', 'Extraction ready'), ('extraction_passed', 'Extraction passed'), ('needs_review', 'Needs review'), ('promoted', 'Promoted'), ('failed', 'Failed')], db_index=True, default='new', max_length=32),
        ),
    ]
