# Generated by Django 6.0.3 on 2026-04-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditationapp', '0008_session_recurrence_session_recurrence_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidaterecord',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('keyword_passed', 'Keyword passed'), ('quality_passed', 'Quality passed'), ('structured_ready', 'Structured ready'), ('extraction_ready', 'Needs enrichment'), ('extraction_passed', 'Extraction passed'), ('needs_review', 'Needs review'), ('promoted', 'Promoted'), ('failed', 'Failed')], db_index=True, default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='extractionattempt',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('keyword_passed', 'Keyword passed'), ('quality_passed', 'Quality passed'), ('structured_ready', 'Structured ready'), ('extraction_ready', 'Needs enrichment'), ('extraction_passed', 'Extraction passed'), ('needs_review', 'Needs review'), ('promoted', 'Promoted'), ('failed', 'Failed')], db_index=True, default='new', max_length=32),
        ),
    ]
