# Generated by Django 6.0.3 on 2026-05-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditationapp', '0009_alter_candidaterecord_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidaterecord',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('keyword_passed', 'Keyword passed'), ('structured_ready', 'Structured ready'), ('extraction_ready', 'Needs enrichment'), ('extraction_passed', 'Extraction passed'), ('needs_review', 'Needs review'), ('promoted', 'Promoted'), ('failed', 'Failed')], db_index=True, default='new', max_length=32),
        ),
        migrations.AlterField(
            model_name='extractionattempt',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('keyword_passed', 'Keyword passed'), ('structured_ready', 'Structured ready'), ('extraction_ready', 'Needs enrichment'), ('extraction_passed', 'Extraction passed'), ('needs_review', 'Needs review'), ('promoted', 'Promoted'), ('failed', 'Failed')], db_index=True, default='new', max_length=32),
        ),
    ]
